// This file has been autogenerated using component_parser.
#include "component_registry.h"
#include "ecs.h"

#define ENTITY_SET_TAG(world, entity, component)\
	world->entities.component_map[entity.as.index].bytes[component / COMPONENTBITMAP_SLOTSIZE] |= (component % COMPONENTBITMAP_SLOTSIZE)

#define ENTITY_UNSET_TAG(world, entity, component)\
	world->entities.component_map[entity.as.index].bytes[component / COMPONENTBITMAP_SLOTSIZE] &= ~(component % COMPONENTBITMAP_SLOTSIZE);

#define ENTITY_ADD_DENSE(world, entity, container, data, component_tag)\
	if (!entity_is_alive(world, entity))\
		return &world->components.container[0];\
	world->components.container[entity.as.index] = data;\
	ENTITY_SET_TAG(world, entity, component_tag);\
	return &world->components.container[entity.as.index]

#define ENTITY_ADD_SPARSE(world, entity, container, data, component_tag)\
	if (!entity_is_alive(world, entity))\
		return &world->components.container[0];\
        size_t index = world->components.container##_count++;\
	world->components.container##_entity[index] = entity.as.index;\
	world->components.container[index] = data;\
	ENTITY_SET_TAG(world, entity, component_tag);\
	return &world->components.container[index]

#define ENTITY_ADD_FLAG(world, entity, container, data, component_tag)\
	if (!entity_is_alive(world, entity))\
		return;\
	ENTITY_SET_TAG(world, entity, component_tag);

#define ENTITY_REMOVE(world, entity, component_tag)\
	if (!entity_is_alive(world, entity))\
		return;\
	ENTITY_UNSET_TAG(world, entity, component_tag);

#define ENTITY_REMOVE_SPARSE(world, entity, component_tag)\
	if (!entity_is_alive(world, entity))\
		return;\
	ENTITY_UNSET_TAG(world, entity, component_tag);

Position* entity_add_position(struct world* _world, union entity _entity, Position position) { ENTITY_ADD_DENSE(_world, _entity, position, position, COMPONENT_POSITION); }
void entity_remove_position(struct world* _world, union entity _entity) { ENTITY_REMOVE(_world, _entity, COMPONENT_POSITION) }

Stats* entity_add_stats(struct world* _world, union entity _entity, Stats stats) { ENTITY_ADD_DENSE(_world, _entity, stats, stats, COMPONENT_STATS); }
void entity_remove_stats(struct world* _world, union entity _entity) { ENTITY_REMOVE(_world, _entity, COMPONENT_STATS) }

Renderable* entity_add_renderable(struct world* _world, union entity _entity, Renderable renderable) { ENTITY_ADD_DENSE(_world, _entity, renderable, renderable, COMPONENT_RENDERABLE); }
void entity_remove_renderable(struct world* _world, union entity _entity) { ENTITY_REMOVE(_world, _entity, COMPONENT_RENDERABLE) }

void entity_add_player(struct world* _world, union entity _entity) { ENTITY_ADD_FLAG(_world, _entity, player, player, COMPONENT_PLAYER); }
void entity_remove_player(struct world* _world, union entity _entity) { ENTITY_REMOVE(_world, _entity, COMPONENT_PLAYER) }

Poisoned* entity_add_poisoned(struct world* _world, union entity _entity, Poisoned poisoned) { ENTITY_ADD_SPARSE(_world, _entity, poisoned, poisoned, COMPONENT_POISONED); }
void entity_remove_poisoned(struct world* _world, union entity _entity) { ENTITY_REMOVE(_world, _entity, COMPONENT_POISONED) }

