#include <stdio.h>
#include <ctype.h>

#define OUT_FILE "include/components.h"
#define HEADER_GUARD "COMPONENTS_H"
#define COMP_NAME "Component"
#define ENUM_NAME "ComponentType"
#define ENUM_FORMAT "  C_%s,\n"
#define MAX_TYPE_C 128

#include "components.h"
int STRUCT(FILE* f, const char* name, const char* fields[]);
void generate_components(FILE* f) {
	size_t len = sizeof(components) / sizeof(ComponentMeta);
	for (size_t i = 0; i < len; i++)
		STRUCT(f, components[i].name, components[i].fields);
}


char types[MAX_TYPE_C][MAX_TYPE_C] = {0};
char types_upper[MAX_TYPE_C][MAX_TYPE_C] = {0};
char types_snake[MAX_TYPE_C][MAX_TYPE_C] = {0};
size_t types_c = 0;

void generate_type_lookup(FILE* f);
int main(void) {
	FILE* f = fopen(OUT_FILE, "w");
	fprintf(f, "#ifndef "HEADER_GUARD"\n");
	fprintf(f, "#define "HEADER_GUARD"\n");
	fprintf(f, "// THIS FILE IS AUTOGENERATED.\n\n");
	generate_components(f);
	generate_type_lookup(f);
	fprintf(f, "\n#endif // "HEADER_GUARD);
	fclose(f);
}

void add_type(const char* name) {
	size_t i = 0;
	while(name[i] != '\0') {
		types[types_c][i] = name[i];
		i++;
	}
	types[types_c][i] = '\0';
}

void add_uppercase(const char* name) {
	size_t i = 0;
	while(name[i] != '\0') {
		types_upper[types_c][i] = toupper(name[i]);
		i++;
	}
	types_upper[types_c][i] = '\0';
}

void add_camel_case(const char* name) {
	size_t i = 0;
	size_t ci = 0;
	while(name[ci] != '\0') {
		char n = tolower(name[ci]);
		if (n != name[ci] && ci != 0) {
			types_snake[types_c][i] = '_';
			i++;
		}
		types_snake[types_c][i] = n;
		ci++;
		i++;
	}
	types_snake[types_c][i] = '\0';
}

int STRUCT(FILE* f, const char* name, const char* fields[]) {
	int i = 0;
	fprintf(f, "typedef struct {", name);
	while (fields[i]) {
		fprintf(f, " %s;", fields[i]);
		i++;
	}
	fprintf(f, " } %s;\n", name);
	add_type(name);
	add_uppercase(name);
	add_camel_case(name);
	types_c++;
}

void generate_type_lookup(FILE* f) {
	fprintf(f, "\ntypedef enum {\n");
	for (size_t i = 0; i < types_c; i++)
		fprintf(f, ENUM_FORMAT, types_upper[i]);
	fprintf(f, "} "ENUM_NAME";\n\n");

	fprintf(f, "typedef struct {\n");
	fprintf(f, "  "ENUM_NAME" type;\n");
	fprintf(f, "  union {\n");
	for (size_t i = 0; i < types_c; i++)
		fprintf(f, "    %s %s;\n", types[i], types_snake[i]);
	fprintf(f, "  } as;\n");
	fprintf(f, "} "COMP_NAME";\n");
}
