#include <stdlib.h>
#include <stdio.h>
#include <stdbool.h>

#include "c_tokenizer.c"
#include "c_parser.c"

#define foreach(type, iterator, start) for (type * iterator = (start); iterator; iterator = iterator -> next)

FILE* file_header;
FILE* file_impl;

const char* HEADER_GUARD_OPEN = "// This file is autogenerated.\n"
	"#ifndef META_H\n"
	"#define META_H\n\n";
const char* HEADER_GUARD_CLOSE = "\n#endif // META_H_";

void print_metatypes() {
	fprintf(file_header, "typedef enum {\n");
	fprintf(file_header, "  METATYPE_Unknown,\n");
	foreach(TypeIdent, ty, type_idents) {
		fprintf(file_header, "  METATYPE_%s,\n", ty->name);
	}
	fprintf(file_header, "} MetaType;\n\n");
}

const char* MEMBER_DEFINITION_TYPEDEF = "typedef struct {\n"
	"  MetaType type;\n"
	"  char* field_name;\n"
	"  int offset;\n"
	"} MemberDefinition;\n\n";

#define offsetof(st, m) ((size_t)&(((st *)0)->m))

void print_reflection() {
	fprintf(file_header, MEMBER_DEFINITION_TYPEDEF);
	foreach(StructDefinition, strct, current_struct) {
		//fprintf(file_header, "extern MemberDefinition members_%s[];\n", strct->name);
		fprintf(file_header, "MemberDefinition members_%s[] = {\n", strct->name);
		foreach(MemberDefinition, member, strct->members) {
			fprintf(file_header, "  { METATYPE_%s, \"%s\", ", member->type, member->field);
			if (strct->is_typedef) {
				fprintf(file_header, "((int)&(((%s*)0)->%s))", strct->name, member->field);
			} else {
				fprintf(file_header, "((int)&(((struct %s*)0)->%s))", strct->name, member->field);
			}
			fprintf(file_header, " },\n");
		}
		fprintf(file_header, "};\n");
	}
}

void print_x_macro() {
	fprintf(file_header, "#define INCLUDE_METATYPE_CASES \\\n");
	foreach(StructDefinition, strct, current_struct) {
		fprintf(file_header, "  X(METATYPE_%s, members_%s)", strct->name, strct->name);
		if (strct->next)
			fprintf(file_header, " \\\n", strct->name);
	}
	fprintf(file_header, "\n");
}

void parse_file(char* filename);
char* file_read(char* filename);

int main() {
	file_header = fopen("meta.h", "w");
	file_impl = fopen("meta.c", "w");
	fprintf(file_header, HEADER_GUARD_OPEN);
	fprintf(file_impl, "// This file is autogenerated.\n");
	fprintf(file_impl, "#include \"meta.h\"\n");
	
	/// PARSE FILES

	parse_file("test.h");

	fprintf(file_impl, "\n");

	/// RUN METAPROGRAM
	print_metatypes();
	print_reflection();
	print_x_macro();

	/// CLOSE EVERYTHING
	fprintf(file_header, HEADER_GUARD_CLOSE);
	fclose(file_impl);
	fclose(file_header);
}

void parse_file(char* filename) {
	fprintf(file_header, "#include \"%s\"\n", filename);

	char* contents = file_read(filename);
	Tokenizer tokenizer;
	tokenizer.at = contents;
	bool parsing = true;
	while(parsing) {
		Token token = token_get(&tokenizer);
		switch (token.type) {
			case TOKEN_EOF: { parsing = false; } break;
			case TOKEN_IDENTIFIER: {
				if (token_equals(token, "DERIVE"))
					parse_derive(&tokenizer);
			} break;
			case TOKEN_UNKNOWN: {} break;
			default: {} break;
		}
	}
}

char* file_read(char* filename) {
	char* result = 0;
	FILE* file = fopen(filename, "r");
	if (file) {
		fseek(file, 0, SEEK_END);
		size_t file_size = ftell(file);
		fseek(file, 0, SEEK_SET);
		result = (char*)malloc(file_size + 1);
		fread(result, file_size, 1, file);
		result[file_size] = '\0';
		fclose(file);
	}
	return result;
}